# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

api_key = app_store_connect_api_key(
  key_id: ENV["APPLE_API_KEY_ID"],
  issuer_id: ENV["APPLE_API_KEY_ISSUER_ID"],
  key_filepath: ENV["APPLE_API_KEY_FILEPATH"],
)

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(workspace: "../../apps/mobile/ios/#{ENV["APP_NAME"]}.xcworkspace", scheme: ENV["IOS_SCHEME_NAME"], output_directory: "./fastlane/build")
    upload_to_testflight(
      api_key: api_key
    )
  end

  desc "Update app's meta in AppStore"
  lane :update_meta do
    deliver(
      api_key: api_key,
      # build_number: '830',
      submit_for_review: false,
      automatic_release: true,
      force: true,
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Update app's screenshots in AppStore"
  lane :update_screenshots do
    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      force: true,
      overwrite_screenshots: false,
      precheck_include_in_app_purchases: false
    )
  end
end

platform :android do
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "../../apps/mobile/android",
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEYSTORE_PASSWORD"]
      }
    )

    apk_path = "../../../apps/mobile/android/app/build/outputs/apk/release/app-release.apk"
    destination_path = "../../../#{ENV["APP_NAME"]}.v.#{ENV["APP_VERSION"]}.b.#{ENV["APP_BUILD_NUMBER"]}.apk"
    FileUtils.mkdir_p(File.dirname(destination_path)) # Создать директорию, если ее нет
    FileUtils.cp(apk_path, destination_path)

    UI.success("APK has been built successfully and saved to #{destination_path}")
  end
end