module.exports = {
  expo: {
    name: process.env.APP_NAME || 'dreamio',
    slug: 'Dreamio',
    version: process.env.APP_VERSION || '1.0.0',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'automatic',
    newArchEnabled: true,
    ios: {
      appleTeamId: process.env.APPLE_TEAM_ID || '',
      buildNumber: process.env.APP_BUILD_NUMBER || '1',
      supportsTablet: false,
      infoPlist: {
        CFBundleDisplayName: 'Dreamio',
        CFBundleAllowMixedLocalizations: true,
        CADisableMinimumFrameDurationOnPhone: true,
        LSApplicationQueriesSchemes: [
          'fb',
          'instagram',
          'twitter',
          'tiktoksharesdk',
        ],
      },
      bundleIdentifier: process.env.IOS_APP_IDENTIFIER || 'com.dreamio',
      config: {
        usesNonExemptEncryption: false,
      },
    },
    android: {
      backgroundColor: '#ffffff',
      versionCode: '1',
      adaptiveIcon: {
        foregroundImage: './assets/icon.png',
        backgroundColor: '#ffffff',
      },
      package: 'me.ilsur.dreamio',
    },
    web: {
      favicon: './assets/icon.png',
    },
    plugins: [
      '@config-plugins/detox',
      'expo-localization',
      [
        'react-native-share',
        {
          ios: ['fb', 'instagram', 'twitter', 'tiktoksharesdk'],
          android: [
            'com.facebook.katana',
            'com.instagram.android',
            'com.twitter.android',
            'com.zhiliaoapp.musically',
          ],
        },
      ],
      [
        'expo-splash-screen',
        {
          backgroundColor: '#ffffff',
          dark: {
            backgroundColor: '#1c1b1f',
          },
        },
      ],
    ],
    locales: {
      'ar-SA': './src/shared/translations_native/ar-SA.json',
      ca: './src/shared/translations_native/ca.json',
      cs: './src/shared/translations_native/cs.json',
      da: './src/shared/translations_native/da.json',
      'de-DE': './src/shared/translations_native/de-DE.json',
      el: './src/shared/translations_native/el.json',
      'en-US': './src/shared/translations_native/en-US.json',
      'en-AU': './src/shared/translations_native/en-AU.json',
      'en-CA': './src/shared/translations_native/en-CA.json',
      'en-GB': './src/shared/translations_native/en-GB.json',
      'es-ES': './src/shared/translations_native/es-ES.json',
      'es-MX': './src/shared/translations_native/es-MX.json',
      fi: './src/shared/translations_native/fi.json',
      'fr-CA': './src/shared/translations_native/fr-CA.json',
      'fr-FR': './src/shared/translations_native/fr-FR.json',
      he: './src/shared/translations_native/he.json',
      hi: './src/shared/translations_native/hi.json',
      hr: './src/shared/translations_native/hr.json',
      hu: './src/shared/translations_native/hu.json',
      id: './src/shared/translations_native/id.json',
      it: './src/shared/translations_native/it.json',
      ja: './src/shared/translations_native/ja.json',
      ko: './src/shared/translations_native/ko.json',
      ms: './src/shared/translations_native/ms.json',
      'nl-NL': './src/shared/translations_native/nl-NL.json',
      no: './src/shared/translations_native/no.json',
      pl: './src/shared/translations_native/pl.json',
      'pt-BR': './src/shared/translations_native/pt-BR.json',
      'pt-PT': './src/shared/translations_native/pt-PT.json',
      ro: './src/shared/translations_native/ro.json',
      ru: './src/shared/translations_native/ru.json',
      sk: './src/shared/translations_native/sk.json',
      sv: './src/shared/translations_native/sv.json',
      th: './src/shared/translations_native/th.json',
      tr: './src/shared/translations_native/tr.json',
      uk: './src/shared/translations_native/uk.json',
      vi: './src/shared/translations_native/vi.json',
      'zh-Hans': './src/shared/translations_native/zh-Hans.json',
      'zh-Hant': './src/shared/translations_native/zh-Hant.json',
    },
  },
}
