# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

api_key = app_store_connect_api_key(
  key_id: ENV["APPLE_API_KEY_ID"],
  issuer_id: ENV["APPLE_API_KEY_ISSUER_ID"],
  key_filepath: ENV["APPLE_API_KEY_FILEPATH"],
)